#!/bin/bash

function log
{

	#turn off traceback
	logstate=`echo $- | grep x`
	set +x

	#log our message to stderr
	if [[ -z $1 ]]; then
		log "bad call to log function!"
	fi
	>&2 echo "[`date`] $1"

	# turn traceback on if it was already on
	if [[ $logstate ]]; then
		set -x
	fi
}


